# Generated by Django 6.1 on 2026-08-16 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField(db_index=True)),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('RELEASED', 'Released'), ('ENDED', 'Ended')], db_index=True, default='UPCOMING', max_length=20)),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genres', to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='movies.movie')),
            ],
            options={
                'db_table': 'movie_genres',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieGenre', to='movies.genre'),
        ),
    ]
